version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - run:
          name: build the app docker image
          command: docker build -t nginx-hello-world .

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
